import {readFile, writeFile} from "node:fs/promises";

/**
 * 이 저장소의 README를 문서 홈과 동기화 · 본문은 유지하고 사이트용 링크만 변환
 * 배포용 라이브러리에는 포함하지 않는 저장소 전용 작업
 */
const source = await readFile(new URL("../README.md", import.meta.url), "utf8");
const content = source
    .replace('src="src/asset/favicon.svg"', 'src="/favicon.svg"')
    .replaceAll("](templates/document/", "](")
    .replaceAll("](LICENSE)", "](https://github.com/minu-ha/for-humanity/blob/main/LICENSE)")
    .replaceAll("](language/README.ko.md)", "](https://github.com/minu-ha/for-humanity/blob/main/language/README.ko.md)");

await writeFile(new URL("../templates/document/README.md", import.meta.url), `<!-- Generated by pnpm sync:readme from the repository README.md. -->\n\n${content}`);
